### PR TITLE
Add pantheon apps

### PR DESCRIPTION
**Pull request by Justinzobel**
:)

### CODE REVIEW

**Comment by streambinder** [comment]
Thank you.
Please, review all the packages manifests your proposing by switching packages `source` to `git` format. Example:
```
source:
    - https://github.com/elementary/videos/archive/2.6.3.tar.gz : 520b791a518c4bae0ddd6a3497d15c845904da2c682505e6e974364c1b3896d8
```
to
```
source:
    - git|https://github.com/elementary/videos.git : 2.6.3
```

Once done, I will merge it.

**Comment by Justinzobel** [comment]
Curious as to your reason for that, tarballs are one file download whereas git will take time to pull all objects.

**Comment by streambinder** [comment]
There's no real oustanding reason for that, just a convention inherited by Solus development team.

**Comment by Justinzobel** [comment]
> There's no real oustanding reason for that, just a convention inherited by
> Solus development team.

95% of applications in the Solus repo are from tarballs. I should know as I
created a lot of them.

**Comment by streambinder** [comment]
In few packages I noticed they were using it and I enjoyed that, as it prevents the developer from always downloading the tarball, getting the SHA sum and writing them manually in the yaml manifest. With Git version of `source` keyword you only need to replace repository tag/commit.

**Comment by Justinzobel** [comment]
That's where the yupdate.py script makes that extremely easy. It's in the
common repository under Scripts on the Solus git infrastructure.

**Comment by streambinder** [comment]
Uhm, that could be useful. How does it work?

**Comment by Justinzobel** [comment]
yupdate.py $newvsersionno $urloftarball

It will go fetch the tarball and update package.yml then you can build.
Done.

**Comment by streambinder** [comment]
Uhm. I'll maybe adopt it.
In the meantime, I'm going to merge your PR: are you going to add other applicaitons or you're done with those?

**Comment by Justinzobel** [comment]
I'm done for now.

**Pull request merged**
